#!/usr/bin/env python3
"""
Pattern Scout — turn raw transcripts into ranked pattern candidates.

Given a meeting transcript, 1:1 notes, or demo recap (Markdown/plain text),
Pattern Scout bundles the source with the editorial rubric, existing issue
map, and series roadmap into a single LLM-ready prompt artifact. Paste the
output into Copilot Chat (or any LLM) to get back structured pattern
candidates disaggregated and ranked.

Usage:
    python3 scripts/pattern_scout.py path/to/transcript.md
    python3 scripts/pattern_scout.py path/to/transcript.md --out candidates/my-session.md
    python3 scripts/pattern_scout.py --init-template candidates/new.yaml

Outputs (default):
    candidates/<input-stem>__scout.md   — ready-to-paste LLM prompt
    candidates/<input-stem>__spec.yaml  — blank candidate template

The scout does NOT call an LLM — it produces a single well-formed prompt
with all the context the LLM needs (editorial rubric, published issue
titles, roadmap gaps) so results are consistent across editors.
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLAYBOOK = REPO_ROOT / "PRODUCTION_PLAYBOOK.md"
SERIES_ROADMAP = REPO_ROOT / "series_plan" / "SERIES_ROADMAP.md"
ISSUES_DIR = REPO_ROOT / "issues"
DEFAULT_OUT = REPO_ROOT / "candidates"

RUBRIC = """\
## Editorial rubric (The Cheat Code)

1. **Lead with the customer scenario.** Never write a demo recap. What
   problem was the customer trying to solve? What broke before the pattern?
2. **Disaggregate.** A single agent demo usually contains 2–4 reusable
   patterns. Pull them apart — one issue per pattern, not one issue per demo.
3. **Pattern shape.** Classify each candidate as:
      - one-shot  (single prompt → single action)
      - chained   (multi-step prompt chain with handoffs)
      - scoped    (boundary/guardrail pattern)
      - grounded  (retrieval/search/RAG pattern)
      - gated     (human-in-the-loop / approval pattern)
      - pipeline  (event → summarize → distribute)
      - orchestr. (multi-agent orchestration)
4. **Cadence.** Odd issues are 🧠 Conceptual (names the pattern, explains
   why, frames architecture). Even issues are 🔧 Practical (build it in
   Copilot Studio step-by-step). Conceptual/practical pairs live as arcs.
5. **CSA speed test.** Every section must answer: "How does this make me
   faster as a CSA?" If it doesn't, cut it.
6. **Attribution.** Full name of the builder in every issue — no anonymous
   patterns.
7. **Reusability score (1–5).**
      5 = applies to most ABS engagements, minimal adaptation
      4 = applies to a whole industry/segment
      3 = applies to a cluster of similar customers
      2 = one customer, interesting pattern
      1 = bespoke, not portable
"""

PROMPT_TEMPLATE = """\
# Pattern Scout prompt — {stem}

You are Pattern Scout, an editorial agent for *The Cheat Code*, an internal
Microsoft newsletter that publishes reusable agentic patterns for Copilot
Chat. Your job: read the source material below and emit a ranked list of
candidate patterns ready to enter the editorial backlog.

## Source material

````
{source}
````

{rubric}

## Published issues (do not duplicate)

{issue_map}

## Series roadmap (match to gaps where possible)

{roadmap}

## Your task

Emit candidates as a YAML list. One entry per pattern — disaggregate
demos that contain multiple patterns. Example:

```yaml
candidates:
  - title: Short, pattern-first name (not a feature name)
    pattern_shape: one-shot | chained | scoped | grounded | gated | pipeline | orchestr.
    cadence_fit: conceptual | practical | both
    customer: Customer name (or "multiple" / "internal")
    builder: Full name of builder
    scenario: 2–3 sentences, customer-first. What broke before this?
    design_decisions:
      - Numbered decisions that make this pattern work
      - Focus on transferable lessons, not config screenshots
    reusability: 1–5 integer
    related_issues: [list of existing issue numbers this extends or contrasts]
    suggested_arc: existing arc name or "new"
    notes: Anything the editor should know (sensitivities, attribution gaps, etc.)
```

Rank candidates by reusability (desc), then by strategic fit with open
roadmap gaps. Skip patterns with reusability < 3 unless they illustrate a
concept no published issue has covered.

Generated: {today}
"""

CANDIDATE_TEMPLATE = """\
# Candidate patterns — draft
# Generated by Pattern Scout. Fill in after running the prompt artifact
# through Copilot Chat / your LLM of choice, then move approved candidates
# into series_plan/ and update SERIES_ROADMAP.md.

candidates:
  - title: ""
    pattern_shape: ""  # one-shot | chained | scoped | grounded | gated | pipeline | orchestr.
    cadence_fit: ""    # conceptual | practical | both
    customer: ""
    builder: ""
    scenario: ""
    design_decisions:
      - ""
    reusability: 0     # 1-5
    related_issues: []
    suggested_arc: ""
    notes: ""
"""


def _issue_map() -> str:
    """Read published issue HTML titles to build a dedupe table."""
    rows = []
    for p in sorted(ISSUES_DIR.glob("the_cheat_code_issue_*.html")):
        num_match = re.search(r"issue_(\d{3})", p.name)
        if not num_match:
            continue
        num = num_match.group(1)
        try:
            html = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        title_match = re.search(r"<title>([^<]+)</title>", html)
        title = title_match.group(1).strip() if title_match else "(no title)"
        # Drop the "— The Cheat Code #NNN" suffix for readability
        title = re.sub(r"\s*[—\-]\s*The Cheat Code.*$", "", title, flags=re.I)
        rows.append(f"| #{num} | {title} |")
    if not rows:
        return "| _none_ | _no issues found in issues/_ |"
    return "| Issue | Title |\n|-------|-------|\n" + "\n".join(rows)


def _roadmap_excerpt() -> str:
    if not SERIES_ROADMAP.exists():
        return "_(series_plan/SERIES_ROADMAP.md not found)_"
    text = SERIES_ROADMAP.read_text(encoding="utf-8", errors="replace")
    # Include just the arc summaries — usually the first ~180 lines
    lines = text.splitlines()[:180]
    return "\n".join(lines)


def build_prompt(source_path: Path) -> str:
    source = source_path.read_text(encoding="utf-8", errors="replace")
    return PROMPT_TEMPLATE.format(
        stem=source_path.stem,
        source=source.strip(),
        rubric=RUBRIC,
        issue_map=_issue_map(),
        roadmap=_roadmap_excerpt(),
        today=date.today().isoformat(),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", nargs="?", help="Path to transcript / notes file")
    parser.add_argument("--out", type=Path, help="Output path for prompt artifact")
    parser.add_argument("--init-template", type=Path, help="Write a blank candidates YAML template to this path and exit")
    args = parser.parse_args()

    if args.init_template:
        args.init_template.parent.mkdir(parents=True, exist_ok=True)
        args.init_template.write_text(CANDIDATE_TEMPLATE, encoding="utf-8")
        print(f"Wrote blank candidate template: {args.init_template}")
        return 0

    if not args.source:
        parser.print_help()
        return 2

    source_path = Path(args.source)
    if not source_path.exists():
        print(f"error: source file not found: {source_path}", file=sys.stderr)
        return 1

    prompt = build_prompt(source_path)
    out = args.out or (DEFAULT_OUT / f"{source_path.stem}__scout.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(prompt, encoding="utf-8")

    spec_path = out.with_name(f"{source_path.stem}__spec.yaml")
    if not spec_path.exists():
        spec_path.write_text(CANDIDATE_TEMPLATE, encoding="utf-8")

    print(f"Wrote prompt artifact: {out}")
    print(f"Wrote blank spec:      {spec_path}")
    print()
    print("Next: paste the prompt artifact into Copilot Chat / your LLM,")
    print("then capture approved candidates in the spec YAML.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
